services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: adminer
      MYSQL_DATABASE: test_auth
      MYSQL_PASSWORD: adminer
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: